import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import authRoutes from "./routes/authRoutes.js";
import applicationRoutes from "./routes/applicationRoutes.js";
import logRoutes from "./routes/logRoutes.js";
import { errorHandler } from "./middlewares/errorHandler.js";
import dotenv from "dotenv";
dotenv.config({ quiet: true });
const app = express(); 
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true })); 
app.use(express.json()); 
app.use(cookieParser()); 
app.use("/api/users", authRoutes); 
app.use("/api/applications", logRoutes); 
app.use("/api/applications", applicationRoutes);
app.use(errorHandler); 
export default app; 
